[theme]
mode              = "dark"
source            = "wallpaper"
wallpaper_scheme  = "m3-content"

[wallpaper]
enabled               = true
transition_on_startup = true
directory             = "~/Pictures/Wallpapers"

[wallpaper.automation]
enabled                      = true
interval_seconds             = 1800 # 30min
order                        = "random" # random | alphabetical
recursive                    = true     # scan subdirectories when selecting random wallpapers

[nightlight]
enabled              = true
force                = false   # force night mode from startup

temperature_day   = 6500       # Kelvin (must be > temperature_night by at least 100)
temperature_night = 3500       # Kelvin

[location]
auto_locate = false            # resolve coordinates from your IP address when true
address     = "Kirland, Washington, USA"    # geocoded when auto_locate = false and non-empty

[weather]
enabled         = true
refresh_minutes = 30
unit            = "imperial"      # metric | imperial
effects         = true          # visual weather effects

[shell]
font_family        = "Maple Mono NF Light"
offline_mode       = false

[bar]
order = ["main"]              # layer-shell creation order

[bar.main]
enabled            = true
position           = "top"

font_family        = "Maple Mono NF Light"

radius             = 24
margin_edge        = 10
margin_ends        = 16
background_opacity = 0.6
shadow             = true

start  = ["launcher", "clock", "wallpaper",  "cpu", "ram", "download"] # upload, disk
center = ["workspaces", "privacy"]
end    = ["media", "notifications", "tray", "volume", "brightness", "battery", "network", "control-center"]

capsule            = true
capsule_fill       = "surface_variant"
capsule_opacity    = 0.8

[widget.clock]
format = "{:%H:%M %a, %d %b}"
tooltip_format = "{:%A, %B %d, %Y}"

[widget.privacy]
type           = "privacy"
hide_inactive  = true

[widget.tray]
drawer = true

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.cpu]
type = "sysmon"
stat = "cpu_usage"

[widget.ram]
type = "sysmon"
stat = "ram_used"

[widget.disk]
type = "sysmon"
stat = "disk_pct"
path = "/"

[widget.download]
type      = "sysmon"
stat      = "net_rx"

[widget.upload]
type      = "sysmon"
stat      = "net_tx"


[plugins]
auto_update = "none"
